// src/ui/wizard/Handoff.tsx
/**
 * The hand-off: every number this tool produces, next to the Configurator cell
 * it belongs in.
 *
 * The Configurator repeats an identical block per period offset by 30 rows, so
 * the cell references below are exact for each period rather than "row 28-ish".
 */

import {
  COUNTER_BASE_ROWS,
  PERIOD_ROW_STRIDE,
  COUNTER_KEYS,
  COUNTER_LABELS,
  LINE_ITEMS,
  cellFor,
  periodMonthsCell,
  storageGiBMonthsForPeriod,
  type PeriodResult,
  type Scenario,
  type ScenarioResult,
} from '../../../lib/engine/index.js';
import { useState } from 'preact/hooks';

import { commercialBool, commercialNumber } from '../store.js';
import { CopyButton } from '../parts.js';
import { monthYear, n, nf1 } from '../format.js';
import { Rich, useT } from '../i18n.js';
import type { T } from '../../../lib/i18n/index.js';

interface Props {
  scenario: Scenario;
  result: ScenarioResult;
}

/** Where a number on this screen came from, which decides how it is drawn. */
type Origin = 'calculated' | 'estimated' | 'stated' | 'none';

/**
 * Value and display string for one line item in one period.
 *
 * The estimated lines matter here: storage is filled in by the tool unless
 * somebody states a figure, and this screen showed a dash for it while the
 * workbook wrote 64.82 into the same cell. A hand-off sheet that disagrees with
 * the file it hands off is worse than one that says nothing.
 */
/**
 * A line item nobody has filled in, in any period.
 *
 * Only the asked ones: `messages` is calculated and `ods` is estimated, so
 * neither is ever empty for want of an answer. Zero across every period is the
 * test, not zero in the one being looked at -- a row that is 0 in period 1 and
 * 3 in period 2 is in use.
 */
function isUnused(scenario: Scenario, item: (typeof LINE_ITEMS)[number]): boolean {
  if (item.source === 'calculated' || item.source === 'estimated') return false;
  return scenario.periods.every((period) =>
    item.source === 'choice'
      ? !commercialBool(period, item.key)
      : commercialNumber(period, item.key) === 0,
  );
}

/** The length the customer gave this period, for the column header. */
function monthsOf(scenario: Scenario, index: number): number {
  return scenario.periods.find((p) => p.index === index)?.months ?? 0;
}

function valueFor(
  t: T,
  scenario: Scenario,
  result: ScenarioResult,
  periodResult: PeriodResult,
  key: string,
): { text: string; origin: Origin } {
  const period = scenario.periods.find((p) => p.index === periodResult.index);
  if (key === 'messages') {
    return { text: n(periodResult.peak.total), origin: 'calculated' };
  }
  if (!period) return { text: '—', origin: 'none' };

  const item = LINE_ITEMS.find((i) => i.key === key);
  if (item?.source === 'choice') {
    return {
      text: commercialBool(period, key) ? t('deployment.yes') : t('deployment.no'),
      origin: 'stated',
    };
  }

  const value = commercialNumber(period, key);
  if (value > 0) return { text: n(value), origin: 'stated' };

  if (item?.source === 'estimated' && key === 'ods') {
    // GiB-months: what the database held at the end of each month of the
    // period, added up. See storage.ts for why that and not the fullest month.
    const giBMonths = storageGiBMonthsForPeriod(result, periodResult.index);
    if (giBMonths > 0) return { text: nf1.format(giBMonths), origin: 'estimated' };
  }
  return { text: '—', origin: 'none' };
}

export function Handoff({ scenario, result }: Props) {
  const t = useT();
  // Collapsed by default: on a typical estimate 13 of the 15 asked line items
  // are dashes, and they bury the two that are not.
  const [showUnused, setShowUnused] = useState(false);
  const unused = LINE_ITEMS.filter((item) => isUnused(scenario, item));
  const tsvFor = (periodResult: PeriodResult): string => {
    const period = scenario.periods.find((p) => p.index === periodResult.index);
    const lines: string[] = [
      `${periodMonthsCell(periodResult.index)}	${period?.months ?? ''}	${t('handoff.lengthLabel', {
        index: periodResult.index,
      })}`,
    ];
    for (const item of LINE_ITEMS) {
      if (item.key === 'messages') continue; // D27 is a formula in the workbook.
      const { text } = valueFor(t, scenario, result, periodResult, item.key);
      if (text !== '—') lines.push(`${cellFor(item.baseRow, periodResult.index)}\t${text.replace(/,/g, '')}\t${item.label}`);
    }
    COUNTER_KEYS.forEach((key, i) => {
      lines.push(
        `${cellFor(COUNTER_BASE_ROWS[i]!, periodResult.index)}\t${Math.round(periodResult.peak.counters[key])}\t${COUNTER_LABELS[key]}`,
      );
    });
    return lines.join('\n');
  };

  return (
    <section class="panel">
      <header>
        <h2>{t('handoff.heading')}</h2>
        <span class="sub">{t('handoff.sub')}</span>
      </header>
      <div class="body tight scroll">
        <table>
          <thead>
            <tr>
              <th style="min-width:240px">{t('handoff.col.item')}</th>
              {result.periods.map((p) => (
                <th class="num" key={p.index} style="min-width:130px">
                  {/* The period's own length, beside its number. Every figure
                      in the column is one month's worth, so a header naming
                      only the month read as though the 12 months had been
                      ignored -- they are D21, and the Configurator multiplies
                      by them. */}
                  {/* nowrap so the column sizes to this line rather than
                      breaking it as "Period 1 · 12 / months" -- German is
                      longer again, and a pixel width guessed for one language
                      is wrong in the other. The month below may still wrap. */}
                  <span style="white-space:nowrap">
                    {t.plural('handoff.periodHeading', monthsOf(scenario, p.index), {
                      label: t('contract.periodN', { index: p.index }),
                    })}
                  </span>
                  <div style="font-weight:400;text-transform:none;letter-spacing:0">
                    {t('handoff.periodPeak', {
                      month: monthYear(p.peak.year, p.peak.month),
                      days: p.peak.days,
                    })}
                  </div>
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                {t('handoff.periodLength')}
                <div class="hint" style="margin:0">{t('handoff.months')}</div>
              </td>
              {result.periods.map((p) => {
                const period = scenario.periods.find((s) => s.index === p.index);
                return (
                  <td class="num" key={p.index}>
                    {period?.months ?? '—'}
                    <div class="cell">{periodMonthsCell(p.index)}</div>
                  </td>
                );
              })}
            </tr>

            {LINE_ITEMS.filter((item) => showUnused || !isUnused(scenario, item)).map((item) => (
              <>
                <tr key={item.key} class={item.key === 'messages' ? 'total' : ''}>
                  <td>
                    {item.label}
                    <div class="hint" style="margin:0">
                      {/* Every other row states the unit its quantity is typed
                          in. Messages cannot: the Configurator's unit for it is
                          "per 100K per month", which is how the row is priced,
                          and under a raw 46,009,000 that reads as the unit the
                          figure is in. So this row says what its number is
                          instead. The workbook keeps the Configurator's own
                          wording, where the cell is blank and cannot mislead. */}
                      {item.key === 'messages' ? t('handoff.messages.what') : item.unit}
                      {item.source === 'estimated' && t('handoff.estimated')}
                    </div>
                  </td>
                  {result.periods.map((p) => {
                    const { text, origin } = valueFor(t, scenario, result, p, item.key);
                    return (
                      <td class="num" key={p.index}>
                        <span
                          style={
                            origin === 'none'
                              ? 'color:var(--ink-faint)'
                              : origin === 'calculated'
                                ? 'font-weight:600'
                                : origin === 'estimated'
                                  ? 'font-style:italic'
                                  : ''
                          }
                          title={origin === 'estimated' ? t('handoff.estimateTitle') : undefined}
                        >
                          {text}
                        </span>
                        <div class="cell">{cellFor(item.baseRow, p.index)}</div>
                      </td>
                    );
                  })}
                </tr>

                {/* The nine counters sit directly under Messages in the workbook. */}
                {item.key === 'messages' &&
                  COUNTER_KEYS.map((key, i) => (
                    <tr key={key}>
                      <td style="padding-left:26px">{COUNTER_LABELS[key]}</td>
                      {result.periods.map((p) => (
                        <td class="num" key={p.index}>
                          <span style={p.peak.counters[key] === 0 ? 'color:var(--ink-faint)' : ''}>
                            {n(p.peak.counters[key])}
                          </span>
                          <div class="cell">{cellFor(COUNTER_BASE_ROWS[i]!, p.index)}</div>
                        </td>
                      ))}
                    </tr>
                  ))}
              </>
            ))}

            {/* The rows nobody filled in, counted rather than listed. Never
                dropped: this table is a checklist of Configurator cells, and a
                cell that is empty because nobody has decided yet still has to
                be findable. The nine counters are never in here -- they are one
                contiguous paste block, and a zero hidden out of D28:D36 is a
                stale value left behind in the Configurator. */}
            {unused.length > 0 && (
              <tr>
                <td class="hint" colSpan={1 + result.periods.length}>
                  {t.plural('handoff.unused', unused.length)}{' '}
                  <button
                    class="ghost"
                    style="padding:0 4px;text-decoration:underline"
                    onClick={() => setShowUnused(!showUnused)}
                  >
                    {showUnused ? t('handoff.unused.hide') : t('handoff.unused.show')}
                  </button>
                </td>
              </tr>
            )}

            <tr>
              {/* What the two buttons do, said in the row that holds them. They
                  used to be labelled "Counters" and "All" against one run-on
                  sentence, which is not an explanation of either. */}
              <td class="hint">
                <Rich
                  k="handoff.counters.explain"
                  p={{
                    range: `${cellFor(COUNTER_BASE_ROWS[0]!, 1)}:${cellFor(COUNTER_BASE_ROWS[8]!, 1)}`,
                    stride: PERIOD_ROW_STRIDE,
                  }}
                />
                <div style="margin-top:5px">
                  <Rich k="handoff.all.explain" />
                </div>
              </td>
              {result.periods.map((p) => (
                <td class="num" key={p.index}>
                  <CopyButton
                    label={t('handoff.counters')}
                    title={t('handoff.counters.title', {
                      index: p.index,
                      cell: cellFor(COUNTER_BASE_ROWS[0]!, p.index),
                    })}
                    text={() => COUNTER_KEYS.map((k) => Math.round(p.peak.counters[k])).join('\n')}
                  />{' '}
                  <CopyButton
                    label={t('handoff.all')}
                    title={t('handoff.all.title', { index: p.index })}
                    text={() => tsvFor(p)}
                  />
                </td>
              ))}
            </tr>
          </tbody>
        </table>
      </div>
    </section>
  );
}

// src/c8y/app/results/handoff.component.ts
/**
 * The hand-off: every number this tool produces, next to the Configurator cell
 * it belongs in.
 *
 * The Configurator repeats an identical block per period offset by 30 rows, so
 * the cell references below are exact for each period rather than "row 28-ish".
 */

import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';

import {
  COUNTER_BASE_ROWS,
  COUNTER_KEYS,
  COUNTER_LABELS,
  LINE_ITEMS,
  PERIOD_ROW_STRIDE,
  cellFor,
  periodMonthsCell,
  storageGiBMonthsForPeriod,
  type PeriodResult,
  type Scenario,
  type ScenarioResult,
} from '../../../../lib/engine/index.js';
import { monthYear, n, nf1 } from '../../../../lib/format/index.js';
import type { T } from '../../../../lib/i18n/index.js';
import { commercialBool, commercialNumber } from '../../../../lib/scenario/edits.js';
import { CopyButtonComponent } from '../controls/copy-button.component.js';
import { LocaleService } from '../i18n/locale.service.js';
import { RichComponent } from '../i18n/rich.component.js';
import { TPipe } from '../i18n/t.pipe.js';
import { ScenarioStore } from '../scenario.store.js';

/** Where a number on this screen came from, which decides how it is drawn. */
type Origin = 'calculated' | 'estimated' | 'stated' | 'none';

/**
 * Value and display string for one line item in one period.
 *
 * The estimated lines matter here: storage is filled in by the tool unless
 * somebody states a figure, and this screen showed a dash for it while the
 * workbook wrote 64.82 into the same cell. A hand-off sheet that disagrees with
 * the file it hands off is worse than one that says nothing.
 */
function valueFor(
  t: T,
  scenario: Scenario,
  result: ScenarioResult,
  periodResult: PeriodResult,
  key: string,
): { text: string; origin: Origin } {
  const period = scenario.periods.find(p => p.index === periodResult.index);
  if (key === 'messages') {
    return { text: n(periodResult.peak.total), origin: 'calculated' };
  }
  if (!period) return { text: '—', origin: 'none' };

  const item = LINE_ITEMS.find(i => i.key === key);
  if (item?.source === 'choice') {
    return {
      text: commercialBool(period, key) ? t('deployment.yes') : t('deployment.no'),
      origin: 'stated',
    };
  }

  const value = commercialNumber(period, key);
  if (value > 0) return { text: n(value), origin: 'stated' };

  if (item?.source === 'estimated' && key === 'ods') {
    // GiB-months: what the database held at the end of each month of the
    // period, added up. See storage.ts for why that and not the fullest month.
    const giBMonths = storageGiBMonthsForPeriod(result, periodResult.index);
    if (giBMonths > 0) return { text: nf1.format(giBMonths), origin: 'estimated' };
  }
  return { text: '—', origin: 'none' };
}

@Component({
  selector: 'c8y-mc-handoff',
  standalone: true,
  imports: [CopyButtonComponent, RichComponent, TPipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="mc-panel">
      <header>
        <h2>{{ 'handoff.heading' | t }}</h2>
        <span class="mc-sub-label">{{ 'handoff.sub' | t }}</span>
      </header>
      <div class="mc-body mc-tight mc-scroll">
        <table class="table mc-table">
          <thead>
            <tr>
              <th style="min-width:240px">{{ 'handoff.col.item' | t }}</th>
              @for (column of columns(); track column.index) {
                <th class="text-right" style="min-width:130px">
                  <!-- nowrap so the column sizes to this line rather than
                       breaking it as "Period 1 · 12 / months"; German is longer
                       again. The month below may still wrap. -->
                  <span style="white-space:nowrap">{{ column.label }}</span>
                  <div class="mc-col-sub">{{ column.peak }}</div>
                </th>
              }
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                {{ 'handoff.periodLength' | t }}
                <div class="mc-hint">{{ 'handoff.months' | t }}</div>
              </td>
              @for (cell of lengthRow(); track cell.index) {
                <td class="text-right">
                  {{ cell.months }}
                  <div class="mc-cell">{{ cell.reference }}</div>
                </td>
              }
            </tr>

            @for (row of visibleRows(); track row.key) {
              <tr [class.mc-total]="row.isMessages">
                <td>
                  {{ row.label }}
                  <div class="mc-hint">{{ row.unit }}</div>
                </td>
                @for (cell of row.cells; track cell.index) {
                  <td class="text-right">
                    <span [class]="cell.originClass" [title]="cell.title">{{ cell.text }}</span>
                    <div class="mc-cell">{{ cell.reference }}</div>
                  </td>
                }
              </tr>

              <!-- The nine counters sit directly under Messages in the workbook. -->
              @if (row.isMessages) {
                @for (counter of counters(); track counter.key) {
                  <tr>
                    <td class="mc-indent">{{ counter.label }}</td>
                    @for (cell of counter.cells; track cell.index) {
                      <td class="text-right">
                        <span [class.mc-faint]="cell.zero">{{ cell.text }}</span>
                        <div class="mc-cell">{{ cell.reference }}</div>
                      </td>
                    }
                  </tr>
                }
              }
            }

            <!-- The rows nobody filled in, counted rather than listed. Never
                 dropped: this table is a checklist of Configurator cells, and a
                 cell empty because nobody has decided yet still has to be
                 findable. The nine counters are never in here -- they are one
                 contiguous paste block, and a zero hidden out of D28:D36 is a
                 stale value left behind in the Configurator. -->
            @if (unusedCount() > 0) {
              <tr>
                <td class="mc-hint" [attr.colspan]="1 + columns().length">
                  {{ unusedLabel() }}
                  <button type="button" class="btn btn-link btn-sm" (click)="showUnused.set(!showUnused())">
                    {{ (showUnused() ? 'handoff.unused.hide' : 'handoff.unused.show') | t }}
                  </button>
                </td>
              </tr>
            }

            <tr>
              <!-- What the two buttons do, said in the row that holds them. -->
              <td class="mc-hint">
                <c8y-mc-rich k="handoff.counters.explain" [p]="explainParams()" />
                <div class="m-t-4"><c8y-mc-rich k="handoff.all.explain" /></div>
              </td>
              @for (column of columns(); track column.index) {
                <td class="text-right">
                  <c8y-mc-copy
                    [label]="'handoff.counters' | t"
                    [title]="column.countersTitle"
                    [text]="column.countersText"
                  />
                  <c8y-mc-copy
                    [label]="'handoff.all' | t"
                    [title]="column.allTitle"
                    [text]="column.allText"
                  />
                </td>
              }
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  `,
})
export class HandoffComponent {
  private readonly store = inject(ScenarioStore);
  private readonly locales = inject(LocaleService);

  /**
   * Collapsed by default: on a typical estimate 13 of the 15 asked line items
   * are dashes, and they bury the two that are not.
   */
  readonly showUnused = signal(false);

  /**
   * A line item nobody has filled in, in any period.
   *
   * Only the asked ones: `messages` is calculated and `ods` estimated, so
   * neither is ever empty for want of an answer. Zero across every period is
   * the test, not zero in the one being looked at -- a row that is 0 in period
   * 1 and 3 in period 2 is in use.
   */
  private readonly unused = computed(() => {
    const scenario = this.store.scenario();
    return new Set(
      LINE_ITEMS.filter(
        item =>
          item.source !== 'calculated' &&
          item.source !== 'estimated' &&
          scenario.periods.every(period =>
            item.source === 'choice'
              ? !commercialBool(period, item.key)
              : commercialNumber(period, item.key) === 0,
          ),
      ).map(item => item.key),
    );
  });

  readonly unusedCount = computed(() => this.unused().size);

  readonly unusedLabel = computed(() =>
    this.locales.t().plural('handoff.unused', this.unusedCount()),
  );

  readonly visibleRows = computed(() =>
    this.showUnused() ? this.rows() : this.rows().filter(row => !this.unused().has(row.key)),
  );

  readonly columns = computed(() => {
    const t = this.locales.t();
    const scenario = this.store.scenario();
    return this.store.result().periods.map(period => ({
      index: period.index,
      // The period's own length, beside its number. Every figure in the column
      // is one month's worth, so a header naming only the month read as though
      // the 12 months had been ignored -- they are D21, and the Configurator
      // multiplies by them.
      label: t.plural(
        'handoff.periodHeading',
        scenario.periods.find(p => p.index === period.index)?.months ?? 0,
        { label: t('contract.periodN', { index: period.index }) },
      ),
      peak: t('handoff.periodPeak', {
        month: monthYear(period.peak.year, period.peak.month),
        days: period.peak.days,
      }),
      countersTitle: t('handoff.counters.title', {
        index: period.index,
        cell: cellFor(COUNTER_BASE_ROWS[0]!, period.index),
      }),
      allTitle: t('handoff.all.title', { index: period.index }),
      countersText: () =>
        COUNTER_KEYS.map(key => Math.round(period.peak.counters[key])).join('\n'),
      allText: () => this.tsvFor(period),
    }));
  });

  readonly lengthRow = computed(() =>
    this.store.result().periods.map(period => ({
      index: period.index,
      months: this.store.scenario().periods.find(p => p.index === period.index)?.months ?? '—',
      reference: periodMonthsCell(period.index),
    })),
  );

  readonly rows = computed(() => {
    const t = this.locales.t();
    const scenario = this.store.scenario();
    const result = this.store.result();

    return LINE_ITEMS.map(item => ({
      key: item.key,
      isMessages: item.key === 'messages',
      label: item.label,
      // Every other row states the unit its quantity is typed in. Messages
      // cannot: the Configurator's unit for it is "per 100K per month", which
      // is how the row is priced, and under a raw 46,009,000 that reads as the
      // unit the figure is in. So this row says what its number is instead.
      unit:
        (item.key === 'messages' ? t('handoff.messages.what') : item.unit) +
        (item.source === 'estimated' ? t('handoff.estimated') : ''),
      cells: result.periods.map(period => {
        const { text, origin } = valueFor(t, scenario, result, period, item.key);
        return {
          index: period.index,
          text,
          reference: cellFor(item.baseRow, period.index),
          originClass: `mc-origin-${origin}`,
          title: origin === 'estimated' ? t('handoff.estimateTitle') : '',
        };
      }),
    }));
  });

  readonly counters = computed(() => {
    this.locales.locale();
    const periods = this.store.result().periods;
    return COUNTER_KEYS.map((key, i) => ({
      key,
      label: COUNTER_LABELS[key],
      cells: periods.map(period => ({
        index: period.index,
        text: n(period.peak.counters[key]),
        zero: period.peak.counters[key] === 0,
        reference: cellFor(COUNTER_BASE_ROWS[i]!, period.index),
      })),
    }));
  });

  readonly explainParams = computed(() => ({
    range: `${cellFor(COUNTER_BASE_ROWS[0]!, 1)}:${cellFor(COUNTER_BASE_ROWS[8]!, 1)}`,
    stride: PERIOD_ROW_STRIDE,
  }));

  /** Cell reference, value and label per line -- pasteable straight into a sheet. */
  private tsvFor(periodResult: PeriodResult): string {
    const t = this.locales.t();
    const scenario = this.store.scenario();
    const result = this.store.result();
    const period = scenario.periods.find(p => p.index === periodResult.index);

    const lines: string[] = [
      [
        periodMonthsCell(periodResult.index),
        period?.months ?? '',
        t('handoff.lengthLabel', { index: periodResult.index }),
      ].join('\t'),
    ];

    for (const item of LINE_ITEMS) {
      if (item.key === 'messages') continue; // D27 is a formula in the workbook.
      const { text } = valueFor(t, scenario, result, periodResult, item.key);
      if (text !== '—') {
        lines.push(
          `${cellFor(item.baseRow, periodResult.index)}\t${text.replace(/,/g, '')}\t${item.label}`,
        );
      }
    }

    COUNTER_KEYS.forEach((key, i) => {
      lines.push(
        `${cellFor(COUNTER_BASE_ROWS[i]!, periodResult.index)}\t` +
          `${Math.round(periodResult.peak.counters[key])}\t${COUNTER_LABELS[key]}`,
      );
    });

    return lines.join('\n');
  }
}
